
#List of diet groups
[[groups]]
	color = "#aaffaa"
	decay_multiplier = 0.1
	beneficial = true
	name = "proteins"
	icon = "kubejs:protein"
	gain_multiplier = 0.1
	default_value = 0.7
	order = 0

[[groups]]
	color = "#aaffaa"
	decay_multiplier = 0.1
	beneficial = true
	name = "grains"
	icon = "kubejs:grains"
	gain_multiplier = 0.1
	default_value = 0.7
	order = 0

[[groups]]
	color = "#aaffaa"
	decay_multiplier = 0.1
	beneficial = true
	name = "plant_oil"
	icon = "kubejs:plant_oil"
	gain_multiplier = 0.1
	default_value = 0.7
	order = 0

[[groups]]
	color = "#aaffaa"
	decay_multiplier = 0.1
	beneficial = true
	name = "vegetables"
	icon = "kubejs:fruits_and_vegs"
	gain_multiplier = 0.1
	default_value = 0.7
	order = 0

[[groups]]
	color = "#ffaaaa"
	decay_multiplier = 0.1
	beneficial = false
	name = "sugars"
	icon = "kubejs:diabetes_risks"
	gain_multiplier = 0.1
	default_value = 0.5
	order = 1

[[groups]]
	color = "#ffaaaa"
	decay_multiplier = 0.1
	beneficial = false
	name = "vitamin"
	icon = "kubejs:vitamin_toxicity"
	gain_multiplier = 0.1
	default_value = 0.5
	order = 1

