
[death_penalty]
	#The reduction in percentage applied to all diet groups upon death.
	#Range: 0.0 ~ 1.0
	deathPenaltyLoss = 1.0
	#The method to apply for losses due to death penalties.
	#AMOUNT = Reduce by a flat percentage amount
	#PERCENT = Reduce by a percent of the current value
	#RESET = Reset value to defaults
	#Allowed Values: AMOUNT, PERCENT, RESET
	deathPenaltyMethod = "AMOUNT"
	#The minimum percentage that diet groups can be reduced to upon death.
	#Range: 0.0 ~ 1.0
	deathPenaltyMin = 0.0

[calculation]
	#List of food quality overrides for diet gain values.
	#Format: "modid:name;quality"
	foodOverrides = []
	#The percent reduction in total gain for each diet group consumed at once.
	#Range: 0.0 ~ 1.0
	gainPenaltyPerGroup = 0.15000000596046448
	#The percent reduction in total decay for each diet group decayed at once.
	#Range: 0.0 ~ 1.0
	decayPenaltyPerGroup = 0.15000000596046448

