
[general]
	#Rope consumed for each ladder block built.
	#Range: 0 ~ 20
	ropePerLadder = 2
	#Generated bridges will be raised or lowered by this ammount in blocks.
	#Default is just below user's feet.
	#Range: -1.0 ~ 1.0
	bridgeYOffset = -0.3
	#Slabs consumed for each bridge block built.
	#Range: 0 ~ 10
	slabsPerBridge = 1
	#Max length of bridges made be Grappling Gun.
	#Range: 1 ~ 1000
	maxBridgeDistance = 400
	#How much the Ladder Gun is damaged after creating each ladder.
	#Range: 0 ~ 64
	damageForLadder = 1
	#Percent of slack the bridge will have, causing it to hang.
	#Range: 0 ~ 100
	bridgeDroopFactor = 100
	#Set true to ignore all slope warnings and allow building of very steep bridges.
	ignoreSlopeWarnings = false
	#String consumed for each bridge block built.
	#Range: 0 ~ 20
	ropePerBridge = 2
	#If enabled, all blocks that dare stand in a bridge's way will be broken.
	#Very useful in creative mode.
	breakThroughBlocks = false
	#Wood consumed for each ladder block built.
	#Range: 0 ~ 10
	woodPerLadder = 1
	#How much the Bridge Gun is damaged after creating each ladder.
	#Range: 0 ~ 64
	damageForBridge = 1

