
#Configuration for all carts and cart-like vehicles
[carts]

	#The Plow, an animal pulled machine for tilling soil and creating paths
	[carts.plow]
		#Pull speed modifier activated by sprint key while riding
		#Range: -1.0 ~ 0.0
		slow_speed = -0.65
		#Animals that are able to pull this cart, such as ["minecraft:horse"]
		#An empty list defaults to all which may wear a saddle but not steered by an item
		pull_animals = []

	#The Supply Cart, a type of cart that stores items
	[carts.supply_cart]
		#Pull speed modifier activated by sprint key while riding
		#Range: -1.0 ~ 0.0
		slow_speed = -0.65
		#Animals that are able to pull this cart, such as ["minecraft:horse"]
		#An empty list defaults to all which may wear a saddle but not steered by an item
		pull_animals = []

	#The Animal Cart, a type of cart to haul other animals
	[carts.animal_cart]
		#Pull speed modifier activated by sprint key while riding
		#Range: -1.0 ~ 0.0
		slow_speed = -0.65
		#Animals that are able to pull this cart, such as ["minecraft:horse"]
		#An empty list defaults to all which may wear a saddle but not steered by an item
		pull_animals = []

