
["Ore Generation Settings"]
	#determines if deepslate blobs should generate between y0 - y16
	generateDeepslateBlobs = true
	#determines if default copper ore should generate.
	#Note: this doesn't disable the generation of modded copper ore
	generateCopperOre = false
	#determines if tuff blobs should generate between y0 - y16
	generateTuffBlobs = true

["World Generation Settings"]
	#determines if dripstone caves biome should generate in the world
	#Note: to disable ALL the biomes use hasCaveBiomes instead, don't disable all biomes manually or you will break something
	generateDripstoneCaves = true
	#determines if underwater carvers should spawn below oceans
	generateUnderwaterCarvers = true
	#determines the chance of amethyst geodes to spawn.
	#Note: the lower the number, to common it will be, we don't recommend low values or it may cause laggy world loading
	#Default: 53
	#Range: 0 ~ 100
	amethystGeodeChance = 53
	#determines if lush caves biome should generate in the world
	#Note: to disable ALL the biomes use hasCaveBiomes instead, don't disable all biomes manually or you will break something
	generateLushCaves = true

["Entity Settings"]
	#determines the weight for Axolotls to Spawn.
	#Note: the Weight is the chance for them to spawn
	#Default: 10
	#Range: 0 ~ 100
	axolotlWeight = 2
	#determines the weight for Goats to Spawn.
	#Note: the Weight is the chance for them to spawn
	#Default: 10
	#Range: 0 ~ 100
	goatWeight = 10
	#determines the weight for Glow Squids to Spawn.
	#Note: the Weight is the chance for them to spawn
	#Default: 10
	#Range: 0 ~ 100
	glowSquidWeight = 2
	#determines if glow squids should generate.
	#Note: this option exists for compatibility with Upgrade Aquatic.
	generateGlowSquids = true

["Experimental Settings"]
	#determines the max height for deepslate to generate.
	#Default: 0
	#Range: 0 ~ 32
	deepslateLayerMaxHeight = 0

["World Type Settings"]
	#determines if noise caves should generate.
	#Note: these are not the same ones implemented on the CaveBiomeAPI and only apply for CavesAndCliffs WorldType
	generateNoiseCaves = true
	#determines if ore veins should generate.
	generateOreVeins = false
	#determines if deepslate should generate.
	#Note: you can increase the height of the generation of deepslate using 'deepslateLayerMaxHeight' setting.
	generateDeepslate = true
	#determines if noodle caves should generate.
	generateNoodleCaves = true
	#determines if aquifers should generate.
	#Note: this option should not be disabled since it's prepared for the future world Height increment on this mod, otherwise noise caves will all be filled with water.
	generateAquifers = true

