#Enables the weather forecast system. 
enablesTemperatureForecast = true
#BlackListed mods to kick player
"Mod Blacklist" = []
#Enables sending wanted food message. 
enableDailyKitchen = true
#The max power which steam core can store.Steam Core will cost the power stored without any heat source connected.
#Range: 100.0 ~ 6000000.0
steamCoreMaxPower = 600.0
#SteamCore will cost such heat 20 times per second.
#Range: 0.0 ~ 6000000.0
steamCorePowerIntake = 4.0
#The speed which steam core can provide.
#Range: 0.0 ~ 256.0
steamCoreGeneratedSpeed = 32.0
#The capacity which steam core can provide.
#Range: 0.0 ~ 256.0
steamCoreCapacity = 32.0
#Forces the weather forecast system to be enabled regardless of scenario. 
forceEnableTemperatureForecast = true

