
[general]
	#Remove vanilla recipes that are changed by mod or break mod gameplay (wooden tools, torch)
	removeVanillaRecipes = true
	#Chance of successfull fishing every 1/X tick (randomly)
	#Range: > 1
	fishingNetChance = 3600
	#Aqueduct area of bonemeal effect
	#Range: 0 ~ 15
	aqueductEffectRange = 4
	#Chance of bonemeal efect from aqueduct every 1/X tick (randomly)
	#Range: > 1
	aqueductTickChanceBoneMealEffect = 200
	#Disable use of vanilla crafting table until end of Stone Age
	disableVanillaCraftingTable = true
	#Feeder area of breed effect
	#Range: 0 ~ 15
	feederEffectRange = 4
	#List of blocks that have disabled use until end of stone age
	disabledUseInStoneAgeList = ["minecraft:crafting_table"]
	#Domesticate wild animal after given generations
	#Range: > 1
	domesticateAfterGenerations = 3
	#Chance of finishing recipe in tanning rack
	#Range: 0.001 ~ 1.0
	tanningRackFinishChance = 0.1
	#Chance of breed effect from feeder every 1/X tick
	#Range: > 1
	feederTickChanceBreedAnimal = 200
	#Force tool for wood material - harvestable only with axe
	forceToolForWood = true
	#Remove spawning of vanilla animals like cows, pigs, sheeps
	removeVanillaGeneratedAnimals = false
	#Usage of water per tick when activated aqueduct
	#Range: > 1
	aqueductUsePerTick = 1
	#Fill amount per tick when filling from water source
	#Range: > 1
	aqueductFillPerTick = 4
	#Give player manual on first connect to game
	givePlayerManualOnFirstConnect = false

[structures]
	#Abandoned camp allowed biomes
	abandonedCampAllowedBiomes = []
	#Burial place allowed biomes
	burialPlaceAllowedBiomes = []
	#Burial place spawn chance
	#Range: 4.9E-324 ~ 1.0
	burialPlaceSpawnChance = 0.001
	#Abandoned camp spawn chance
	#Range: 4.9E-324 ~ 1.0
	abandonedCampSpawnChance = 0.001

["mob spawning"]

	["mob spawning".deer]
		#If spawnDeerAllowedBiomes is blacklist
		spawnDeerAllowedBiomesBlacklist = false
		#Spawn max count of mob
		#Range: 1 ~ 100
		spawnDeerMaxCount = 10
		#Enable spawning of mob
		spawnDeerEnable = true
		#Spawn deer in allowed biomes
		spawnDeerAllowedBiomes = ["minecraft:tall_birch_hills", "minecraft:eroded_badlands", "minecraft:taiga_hills", "minecraft:snowy_mountains", "minecraft:wooded_hills", "minecraft:snowy_taiga_mountains", "minecraft:shattered_savanna", "minecraft:modified_jungle_edge", "minecraft:gravelly_mountains", "minecraft:snowy_taiga", "minecraft:savanna", "minecraft:swamp", "minecraft:modified_badlands_plateau", "minecraft:snowy_beach", "minecraft:badlands", "minecraft:forest", "minecraft:bamboo_jungle", "minecraft:snowy_tundra", "minecraft:taiga", "minecraft:giant_tree_taiga", "minecraft:modified_gravelly_mountains", "minecraft:wooded_mountains", "minecraft:birch_forest", "minecraft:dark_forest_hills", "minecraft:sunflower_plains", "minecraft:giant_spruce_taiga_hills", "minecraft:jungle_hills", "minecraft:mountains", "minecraft:giant_tree_taiga_hills", "minecraft:jungle", "minecraft:savanna_plateau", "minecraft:badlands_plateau", "minecraft:snowy_taiga_hills", "minecraft:plains", "minecraft:beach", "minecraft:swamp_hills", "minecraft:wooded_badlands_plateau", "minecraft:jungle_edge", "minecraft:modified_wooded_badlands_plateau", "minecraft:modified_jungle", "minecraft:mountain_edge", "minecraft:ice_spikes", "minecraft:dark_forest", "minecraft:giant_spruce_taiga", "minecraft:bamboo_jungle_hills", "minecraft:birch_forest_hills", "minecraft:shattered_savanna_plateau", "minecraft:tall_birch_forest", "minecraft:taiga_mountains", "minecraft:flower_forest"]
		#Spawn weight of mob
		#Range: 0 ~ 100
		spawnDeerWeight = 20
		#Spawn min count of mob
		#Range: 1 ~ 100
		spawnDeerMinCount = 4

	["mob spawning".boar]
		#Result of breeding after generations in captivity
		boarBreedingResult = "minecraft:pig"
		#Spawn weight of mob
		#Range: 0 ~ 100
		spawnBoarWeight = 10
		#Enable spawning of mob
		spawnBoarEnable = true
		#Spawn min count of mob
		#Range: 1 ~ 100
		spawnBoarMinCount = 4
		#Spawn max count of mob
		#Range: 1 ~ 100
		spawnBoarMaxCount = 6
		#Spawn boar in allowed biomes
		spawnBoarAllowedBiomes = ["minecraft:tall_birch_hills", "minecraft:mountains", "minecraft:taiga_hills", "minecraft:giant_tree_taiga_hills", "minecraft:wooded_hills", "minecraft:jungle", "minecraft:snowy_taiga_mountains", "minecraft:shattered_savanna", "minecraft:modified_jungle_edge", "minecraft:savanna_plateau", "minecraft:gravelly_mountains", "minecraft:snowy_taiga_hills", "minecraft:plains", "minecraft:snowy_taiga", "minecraft:savanna", "minecraft:swamp_hills", "minecraft:swamp", "minecraft:jungle_edge", "minecraft:modified_jungle", "minecraft:mountain_edge", "minecraft:forest", "minecraft:bamboo_jungle", "minecraft:dark_forest", "minecraft:giant_spruce_taiga", "minecraft:bamboo_jungle_hills", "minecraft:taiga", "minecraft:giant_tree_taiga", "minecraft:birch_forest_hills", "minecraft:modified_gravelly_mountains", "minecraft:shattered_savanna_plateau", "minecraft:tall_birch_forest", "minecraft:wooded_mountains", "minecraft:taiga_mountains", "minecraft:birch_forest", "minecraft:flower_forest", "minecraft:dark_forest_hills", "minecraft:sunflower_plains", "minecraft:giant_spruce_taiga_hills", "minecraft:jungle_hills"]
		#If spawnBoarAllowedBiomes is blacklist
		spawnBoarAllowedBiomesBlacklist = false

	["mob spawning"."woolly rhino"]
		#Spawn max count of mob
		#Range: 1 ~ 100
		spawnWoollyRhinoMaxCount = 6
		#Spawn min count of mob
		#Range: 1 ~ 100
		spawnWoollyRhinoMinCount = 2
		#Spawn woolly rhino in allowed biomes
		spawnWoollyRhinoAllowedBiomes = ["minecraft:taiga_hills", "minecraft:snowy_mountains", "minecraft:giant_tree_taiga_hills", "minecraft:snowy_taiga_mountains", "minecraft:shattered_savanna", "minecraft:savanna_plateau", "minecraft:mushroom_field_shore", "minecraft:snowy_taiga_hills", "minecraft:plains", "minecraft:snowy_taiga", "minecraft:beach", "minecraft:savanna", "minecraft:swamp_hills", "minecraft:swamp", "minecraft:snowy_beach", "minecraft:river", "minecraft:mushroom_fields", "minecraft:ice_spikes", "minecraft:frozen_river", "minecraft:snowy_tundra", "minecraft:giant_spruce_taiga", "minecraft:taiga", "minecraft:giant_tree_taiga", "minecraft:shattered_savanna_plateau", "minecraft:taiga_mountains", "minecraft:sunflower_plains", "minecraft:giant_spruce_taiga_hills"]
		#Enable spawning of mob
		spawnWoollyRhinoEnable = true
		#Spawn weight of mob
		#Range: 0 ~ 100
		spawnWoollyRhinoWeight = 10
		#If spawnWoollyRhinoAllowedBiomes is blacklist
		spawnWoollyRhinoAllowedBiomesBlacklist = false

	["mob spawning"."terror bird"]
		#Enable spawning of mob
		spawnTerrorBirdEnable = true
		#If spawnTerrorBirdAllowedBiomes is blacklist
		spawnTerrorBirdAllowedBiomesBlacklist = false
		#Spawn weight of mob
		#Range: 0 ~ 100
		spawnTerrorBirdWeight = 5
		#Spawn terror bird in allowed biomes
		spawnTerrorBirdAllowedBiomes = ["minecraft:tall_birch_hills", "minecraft:modified_jungle", "minecraft:wooded_hills", "minecraft:jungle", "minecraft:shattered_savanna", "minecraft:modified_jungle_edge", "minecraft:forest", "minecraft:savanna_plateau", "minecraft:bamboo_jungle", "minecraft:mushroom_fields", "minecraft:mushroom_field_shore", "minecraft:plains", "minecraft:savanna", "minecraft:dark_forest", "minecraft:bamboo_jungle_hills", "minecraft:birch_forest_hills", "minecraft:shattered_savanna_plateau", "minecraft:tall_birch_forest", "minecraft:jungle_edge", "minecraft:birch_forest", "minecraft:flower_forest", "minecraft:dark_forest_hills", "minecraft:sunflower_plains", "minecraft:jungle_hills"]
		#Spawn max count of mob
		#Range: 1 ~ 100
		spawnTerrorBirdMaxCount = 3
		#Spawn min count of mob
		#Range: 1 ~ 100
		spawnTerrorBirdMinCount = 1

	["mob spawning".coelacanth]
		#Spawn weight of mob
		#Range: 0 ~ 100
		spawnCoelacanthWeight = 5
		#If spawnCoelacanthAllowedBiomes is blacklist
		spawnCoelacanthAllowedBiomesBlacklist = false
		#Enable spawning of mob
		spawnCoelacanthEnable = true
		#Spawn coelacanth in allowed biomes
		spawnCoelacanthAllowedBiomes = ["minecraft:tall_birch_hills", "minecraft:eroded_badlands", "minecraft:taiga_hills", "minecraft:snowy_mountains", "minecraft:wooded_hills", "minecraft:end_midlands", "minecraft:end_barrens", "minecraft:snowy_taiga_mountains", "minecraft:shattered_savanna", "minecraft:modified_jungle_edge", "minecraft:soul_sand_valley", "minecraft:gravelly_mountains", "minecraft:the_void", "minecraft:snowy_taiga", "minecraft:savanna", "minecraft:small_end_islands", "minecraft:modified_badlands_plateau", "minecraft:basalt_deltas", "minecraft:snowy_beach", "minecraft:badlands", "minecraft:forest", "minecraft:bamboo_jungle", "minecraft:mushroom_fields", "minecraft:snowy_tundra", "minecraft:taiga", "minecraft:giant_tree_taiga", "minecraft:modified_gravelly_mountains", "minecraft:wooded_mountains", "minecraft:birch_forest", "minecraft:dark_forest_hills", "minecraft:sunflower_plains", "minecraft:giant_spruce_taiga_hills", "minecraft:desert", "minecraft:jungle_hills", "minecraft:mountains", "minecraft:giant_tree_taiga_hills", "minecraft:jungle", "minecraft:warped_forest", "minecraft:savanna_plateau", "minecraft:badlands_plateau", "minecraft:mushroom_field_shore", "minecraft:snowy_taiga_hills", "minecraft:crimson_forest", "minecraft:plains", "minecraft:beach", "minecraft:end_highlands", "minecraft:desert_lakes", "minecraft:wooded_badlands_plateau", "minecraft:jungle_edge", "minecraft:modified_wooded_badlands_plateau", "minecraft:desert_hills", "minecraft:stone_shore", "minecraft:nether_wastes", "minecraft:the_end", "minecraft:modified_jungle", "minecraft:mountain_edge", "minecraft:ice_spikes", "minecraft:dark_forest", "minecraft:giant_spruce_taiga", "minecraft:bamboo_jungle_hills", "minecraft:birch_forest_hills", "minecraft:shattered_savanna_plateau", "minecraft:tall_birch_forest", "minecraft:taiga_mountains", "minecraft:flower_forest"]
		#Spawn max count of mob
		#Range: 1 ~ 100
		spawnCoelacanthMaxCount = 3
		#Spawn min count of mob
		#Range: 1 ~ 100
		spawnCoelacanthMinCount = 1

	["mob spawning".mouflon]
		#If spawnMouflonAllowedBiomes is blacklist
		spawnMouflonAllowedBiomesBlacklist = false
		#Spawn weight of mob
		#Range: 0 ~ 100
		spawnMouflonWeight = 10
		#Spawn min count of mob
		#Range: 1 ~ 100
		spawnMouflonMinCount = 4
		#Spawn mouflon in allowed biomes
		spawnMouflonAllowedBiomes = ["minecraft:tall_birch_hills", "minecraft:eroded_badlands", "minecraft:mountains", "minecraft:taiga_hills", "minecraft:giant_tree_taiga_hills", "minecraft:wooded_hills", "minecraft:snowy_taiga_mountains", "minecraft:badlands_plateau", "minecraft:gravelly_mountains", "minecraft:snowy_taiga_hills", "minecraft:plains", "minecraft:snowy_taiga", "minecraft:swamp_hills", "minecraft:swamp", "minecraft:wooded_badlands_plateau", "minecraft:modified_badlands_plateau", "minecraft:modified_wooded_badlands_plateau", "minecraft:badlands", "minecraft:mountain_edge", "minecraft:forest", "minecraft:dark_forest", "minecraft:giant_spruce_taiga", "minecraft:taiga", "minecraft:giant_tree_taiga", "minecraft:birch_forest_hills", "minecraft:modified_gravelly_mountains", "minecraft:tall_birch_forest", "minecraft:wooded_mountains", "minecraft:taiga_mountains", "minecraft:birch_forest", "minecraft:flower_forest", "minecraft:dark_forest_hills", "minecraft:sunflower_plains", "minecraft:giant_spruce_taiga_hills"]
		#Result of breeding after generations in captivity
		mouflonBreedingResult = "minecraft:sheep"
		#Enable spawning of mob
		spawnMouflonEnable = true
		#Spawn max count of mob
		#Range: 1 ~ 100
		spawnMouflonMaxCount = 8

	["mob spawning".auroch]
		#Spawn auroch in allowed biomes
		spawnAurochAllowedBiomes = ["minecraft:tall_birch_hills", "minecraft:mountains", "minecraft:taiga_hills", "minecraft:giant_tree_taiga_hills", "minecraft:wooded_hills", "minecraft:snowy_taiga_mountains", "minecraft:shattered_savanna", "minecraft:savanna_plateau", "minecraft:gravelly_mountains", "minecraft:snowy_taiga_hills", "minecraft:plains", "minecraft:snowy_taiga", "minecraft:beach", "minecraft:savanna", "minecraft:snowy_beach", "minecraft:mountain_edge", "minecraft:forest", "minecraft:dark_forest", "minecraft:giant_spruce_taiga", "minecraft:taiga", "minecraft:giant_tree_taiga", "minecraft:birch_forest_hills", "minecraft:modified_gravelly_mountains", "minecraft:shattered_savanna_plateau", "minecraft:tall_birch_forest", "minecraft:wooded_mountains", "minecraft:taiga_mountains", "minecraft:birch_forest", "minecraft:flower_forest", "minecraft:dark_forest_hills", "minecraft:sunflower_plains", "minecraft:giant_spruce_taiga_hills"]
		#Spawn min count of mob
		#Range: 1 ~ 100
		spawnAurochMinCount = 4
		#Enable spawning of mob
		spawnAurochEnable = true
		#Spawn weight of mob
		#Range: 0 ~ 100
		spawnAurochWeight = 10
		#If spawnAurochAllowedBiomes is blacklist
		spawnAurochAllowedBiomesBlacklist = false
		#Spawn max count of mob
		#Range: 1 ~ 100
		spawnAurochMaxCount = 8
		#Result of breeding after generations in captivity
		aurochBreedingResult = "minecraft:cow"

	["mob spawning"."saber tooth tiger"]
		#Spawn min count of mob
		#Range: 1 ~ 100
		spawnSaberToothTigerMinCount = 1
		#Enable spawning of mob
		spawnSaberToothTigerEnable = true
		#Spawn max count of mob
		#Range: 1 ~ 100
		spawnSaberToothTigerMaxCount = 2
		#Spawn saber-tooth tiger in allowed biomes
		spawnSaberToothTigerAllowedBiomes = ["minecraft:tall_birch_hills", "minecraft:taiga_hills", "minecraft:snowy_mountains", "minecraft:giant_tree_taiga_hills", "minecraft:wooded_hills", "minecraft:jungle", "minecraft:snowy_taiga_mountains", "minecraft:shattered_savanna", "minecraft:modified_jungle_edge", "minecraft:savanna_plateau", "minecraft:mushroom_field_shore", "minecraft:snowy_taiga_hills", "minecraft:plains", "minecraft:snowy_taiga", "minecraft:beach", "minecraft:savanna", "minecraft:desert_lakes", "minecraft:jungle_edge", "minecraft:desert_hills", "minecraft:snowy_beach", "minecraft:modified_jungle", "minecraft:forest", "minecraft:bamboo_jungle", "minecraft:mushroom_fields", "minecraft:ice_spikes", "minecraft:snowy_tundra", "minecraft:dark_forest", "minecraft:giant_spruce_taiga", "minecraft:bamboo_jungle_hills", "minecraft:taiga", "minecraft:giant_tree_taiga", "minecraft:birch_forest_hills", "minecraft:shattered_savanna_plateau", "minecraft:tall_birch_forest", "minecraft:taiga_mountains", "minecraft:birch_forest", "minecraft:flower_forest", "minecraft:dark_forest_hills", "minecraft:sunflower_plains", "minecraft:giant_spruce_taiga_hills", "minecraft:desert", "minecraft:jungle_hills"]
		#Spawn weight of mob
		#Range: 0 ~ 100
		spawnSaberToothTigerWeight = 5
		#If spawnSaberToothTigerAllowedBiomes is blacklist
		spawnSaberToothTigerAllowedBiomesBlacklist = false

	["mob spawning".fowl]
		#Enable spawning of mob
		spawnFowlEnable = true
		#If spawnFowlAllowedBiomes is blacklist
		spawnFowlAllowedBiomesBlacklist = false
		#Spawn weight of mob
		#Range: 0 ~ 100
		spawnFowlWeight = 10
		#Spawn max count of mob
		#Range: 1 ~ 100
		spawnFowlMaxCount = 8
		#Result of breeding after generations in captivity
		fowlBreedingResult = "minecraft:chicken"
		#Spawn fowl in allowed biomes
		spawnFowlAllowedBiomes = ["minecraft:tall_birch_hills", "minecraft:eroded_badlands", "minecraft:mountains", "minecraft:taiga_hills", "minecraft:giant_tree_taiga_hills", "minecraft:wooded_hills", "minecraft:jungle", "minecraft:snowy_taiga_mountains", "minecraft:shattered_savanna", "minecraft:modified_jungle_edge", "minecraft:savanna_plateau", "minecraft:badlands_plateau", "minecraft:gravelly_mountains", "minecraft:snowy_taiga_hills", "minecraft:plains", "minecraft:snowy_taiga", "minecraft:beach", "minecraft:savanna", "minecraft:swamp_hills", "minecraft:swamp", "minecraft:wooded_badlands_plateau", "minecraft:jungle_edge", "minecraft:modified_badlands_plateau", "minecraft:modified_wooded_badlands_plateau", "minecraft:snowy_beach", "minecraft:badlands", "minecraft:modified_jungle", "minecraft:mountain_edge", "minecraft:forest", "minecraft:bamboo_jungle", "minecraft:dark_forest", "minecraft:giant_spruce_taiga", "minecraft:bamboo_jungle_hills", "minecraft:taiga", "minecraft:giant_tree_taiga", "minecraft:birch_forest_hills", "minecraft:modified_gravelly_mountains", "minecraft:shattered_savanna_plateau", "minecraft:tall_birch_forest", "minecraft:wooded_mountains", "minecraft:taiga_mountains", "minecraft:birch_forest", "minecraft:flower_forest", "minecraft:dark_forest_hills", "minecraft:sunflower_plains", "minecraft:giant_spruce_taiga_hills", "minecraft:jungle_hills"]
		#Spawn min count of mob
		#Range: 1 ~ 100
		spawnFowlMinCount = 6

	["mob spawning".mammoth]
		#If spawnMammothAllowedBiomes is blacklist
		spawnMammothAllowedBiomesBlacklist = false
		#Spawn max count of mob
		#Range: 1 ~ 100
		spawnMammothMaxCount = 4
		#Spawn weight of mob
		#Range: 0 ~ 100
		spawnMammothWeight = 10
		#Enable spawning of mob
		spawnMammothEnable = true
		#Spawn mammoth in allowed biomes
		spawnMammothAllowedBiomes = ["minecraft:mountains", "minecraft:taiga_hills", "minecraft:snowy_mountains", "minecraft:giant_tree_taiga_hills", "minecraft:snowy_taiga_mountains", "minecraft:shattered_savanna", "minecraft:savanna_plateau", "minecraft:gravelly_mountains", "minecraft:snowy_taiga_hills", "minecraft:plains", "minecraft:snowy_taiga", "minecraft:savanna", "minecraft:desert_lakes", "minecraft:desert_hills", "minecraft:mountain_edge", "minecraft:ice_spikes", "minecraft:snowy_tundra", "minecraft:giant_spruce_taiga", "minecraft:taiga", "minecraft:giant_tree_taiga", "minecraft:modified_gravelly_mountains", "minecraft:shattered_savanna_plateau", "minecraft:wooded_mountains", "minecraft:taiga_mountains", "minecraft:sunflower_plains", "minecraft:giant_spruce_taiga_hills", "minecraft:desert"]
		#Spawn min count of mob
		#Range: 1 ~ 100
		spawnMammothMinCount = 2

[aqueduct]
	#If aqueduct remove water source after draining 1000mB
	aqueductRemoveWaterSource = true
	#List of biomes where aqueduct doesn't remove water source
	infinityWaterSourceBiomeList = ["minecraft:cold_ocean", "minecraft:deep_ocean", "minecraft:river", "minecraft:frozen_ocean", "minecraft:ocean", "minecraft:deep_lukewarm_ocean", "minecraft:frozen_river", "minecraft:lukewarm_ocean", "minecraft:deep_cold_ocean", "minecraft:deep_frozen_ocean", "minecraft:warm_ocean", "minecraft:deep_warm_ocean"]

[Config]
	#If grass bed can sleep
	sleep = false
	"Lit torche" = false
	#If Drying rack need daytime
	"need daytime" = false
	"Make fire" = false

