
[Display]
	# 
	#It decides if player can see items' water level. Default:true
	#决定玩家是否可一查看物品的水分值。默认：true
	displayFoodsWaterLevel = true
	# 
	#Open debug mode. Default:false
	#开启调试模式。默认：false
	debugMode = false
	# 
	#It decides if player can see water saturation level. Default:false
	#决定玩家是否可以看到饱和水分值。默认：false
	displayWaterSaturationLevel = false

