
[Misc]
	# 
	#It decides if players' water level would reset in death.
	#决定玩家死亡时是否回复水分值。默认：true
	#Default:true
	resetWaterLevelInDeath = true
	# 
	#finalReducingValue = basicValue * waterReducingRate.(DoubleValue)
	#最终水分值消耗量 = 基础值 * 水分掉落率(本项值).(双浮点类型) 默认：1.0
	#Default:1.0
	#Range: 0.0 ~ 1000.0
	waterReducingRate = 1.0

["Drink Water Block"]
	# 
	#The duration of poison effect when player drink water from water block.(value * 0.05 = seconds)  Default:200
	#玩家右键水方块时获得中毒效果的持续时间（这个值 * 0.05 = 秒数）。默认：200
	#Range: 0 ~ 10800000
	poisonDebuffDuration = 100
	# 
	#The probability of thirst effect when player drink water block water block.  Default:0.8
	#玩家右键水方块时获得口渴效果的概率。默认：0.8
	#Range: 0.0 ~ 1.0
	thirstDebuffProbability = 1.0
	# 
	#The duration of thirst effect when player drink water from water block.(value * 0.05 = seconds)  Default:1200
	#玩家右键水方块时获得口渴效果的持续时间（这个值 * 0.05 = 秒数）。默认：1200
	#Range: 0 ~ 10800000
	thirstDebuffDuration = 1200
	# 
	#The probability of poison effect when player drink water block water block.  Default:0.05
	#玩家右键水方块时获得中毒效果的概率。默认：0.05
	#Range: 0.0 ~ 1.0
	poisonDebuffProbability = 0.05

["Effect Punishment"]
	#  
	#It is the slowness effect amplifier of the effect punishment when player's water level is too low. -1 means canceling this effect. Default:0
	#在水分很低时玩家受到缓慢药水效果的等级。-1代表取消该效果。默认：0
	#Range: -1 ~ 999999
	slownessEffectAmplifier = -1
	#  
	#It is the weakness effect amplifier of the effect punishment when player's water level is too low. -1 means canceling this effect. Default:0
	#在水分很低时玩家受到虚弱药水效果的等级。-1代表取消该效果。默认：0
	#Range: -1 ~ 999999
	weaknessEffectAmplifier = 0

